// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Switch, GridBox, ListView, ScrollView, HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { LunaLibraryGlobalSettings } from "gallery_settings.slint";

export component PageComponent inherits VerticalBox {
    in property <string> title: @tr("default title");
    in property <string> description: @tr("default description");
    in property <bool> is-page-enabled: true;
    in property <bool> show-enable-page-widgets-switch: false; // TODO adapt these switches
    in property <bool> show-enable-read-only: false;

    accessible-role: tab-panel;
    accessible-label: root.title;

    HorizontalBox { 

        //preferred-height: 50px;
        alignment: center;

        Text {
            font-size: 20px;
            text <=> root.title;
            vertical-alignment: center;
        }

        // Spacer
        Rectangle { }

        if show-enable-page-widgets-switch: Switch {
            horizontal-stretch: 0;
            text: @tr("Widgets enabled");
            checked <=> LunaLibraryGlobalSettings.widgets-enabled;
            enabled: true;
        }

        if show-enable-read-only: Switch {
            horizontal-stretch: 0;
            text: @tr("Widgets read-only");
            checked <=> LunaLibraryGlobalSettings.widgets-read-only;
            enabled: true;
        }

        Switch {
            horizontal-stretch: 0;
            text: @tr("Dark Mode");
            checked: Palette.color-scheme == ColorScheme.dark;
            toggled => {
                Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
            }
        }
    }

    @children
}