name: Tracking Issue
description: Track large pull requests
assignees: 
- AndreasTar
title: "[TRACKING] <title>"
labels: tracking
body:
  - type: input
    id: widget
    attributes:
      label: Target Widget
      description: The app widget which this pull request will affect when merged. If multiple, seperate with comma.
      placeholder: "Example: Number Converter"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Decription
      placeholder: "Example: Changing the rabbits widget."
      description: A clear and full description of what the pull request want to achieve.
    validations:
      required: true
  - type: textarea
    id: roadmap
    attributes:
      label: Roadmap
      placeholder: "Example: - [ ] Eat carrots"
      description: A todo list of items to complete before merging the pull request.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      placeholder: "Planting carrots for the rabbits."
      description: Any other context not fitting into the other sections.
    validations:
      required: false
