
import { PageComponent } from "..\..\helpers\page_component.slint";
//import { GlobalConversionCallback } from "..\..\helpers\global_callbacks.slint";

//    Simple_AMPM, //  8:00 pm |  8:00 am
//    Full_AMPM,   // 08:00 pm | 08:00 am
//    Army_AMPM,   // 20:00 pm | 08:00 am
//    Simple,     // 20:00     |  8:00
//    Army,       // 20:00     | 08:00
enum HourStampType {
    Simple_AMPM,
    Full_AMPM,
    Army_AMPM,
    Simple,
    Army,
}

struct HourCell {
    hour_num: int, // 0 - 24
    hour_type: HourStampType,
    time_signature: string, // 8:00am / 20:00 / etc
    is_selected: bool,
    is_current: bool,
}

struct DayCell {
    day_num: int, // 1-31 unless its 30 day or february etc
    in_month: bool,
    is_today: bool,
    is_selected: bool,
}

struct MonthCell {
    month_num: int, // 1-12
    in_year: bool,
    is_current: bool,
    is_selected: bool,
}

struct EventCell {
    // idk what it should store yet, and if it needs to be on the slint side at all
}

// Cells that will be present in the daily view
component HourCellButton inherits Rectangle {
    in property <HourCell> hour_data;

    callback hour_clicked(int);

    pure function convert_time_to_signature(hour: int) -> string {
        return    root.hour_data.hour_type == HourStampType.Simple_AMPM ? "1" 
                : root.hour_data.hour_type == HourStampType.Full_AMPM   ? "2" 
                : root.hour_data.hour_type == HourStampType.Army_AMPM   ? "3" 
                : root.hour_data.hour_type == HourStampType.Simple      ? "4" 
                : root.hour_data.hour_type == HourStampType.Army        ? "5" 
                : "6";
    }

    // TODO add more cases for is_today & has_hover etc
    // colors are for testing
    background: root.hour_data.is_selected                ? white
              : ta.has-hover                              ? blue
              : Math.mod(root.hour_data.hour_num, 2) == 0 ? red 
              : green; 

    ta := TouchArea { clicked => { root.hour_clicked(root.hour_data.hour_num); } }

    // TODO add more cases for is_today & has_hover etc
    Text {
        width: 100%;
        height: 100%;
        text: convert_time_to_signature(root.hour_data.hour-num);
        font-size: 13px;
        color: root.hour_data.is_selected ? white
             : root.hour_data.is_current  ? #2266cc
             : #bbbbbb;
        horizontal-alignment: left;
        vertical-alignment: top;
    }
}

// Cells that will be present in the Monthly and Yearly view
component DayCellButton inherits Rectangle {
    in property <DayCell> day_data;
    in property <bool> visible_days_num: true;

    

    callback day_clicked(int);

    border-radius: 12px;
    border-color: ghostwhite;

    // TODO add more cases for is_today & has_hover etc
    background: root.day_data.is_selected ? #4A90E2
              : root.day_data.is_today    ? #ddeeff
              : ta.has_hover              ? #1258a2
              : transparent;

    ta := TouchArea { clicked => { root.day_clicked(root.day_data.day_num); } }

    // TODO add more cases for is_today & has_hover etc
    Text {
        text: root.day_data.day_num;
        visible: visible_days_num;
        font-size: 14px;
        font-weight: FontWeight.semi-bold;
        color: root.day_data.is_selected ? white
             : root.day_data.is_today    ? #2266cc
             : root.day_data.in_month    ? #d6d6d6
             : #bbbbbb;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}

// Cells that will be present in the Yearly view
component MonthCellButton inherits Rectangle {

    in property <MonthCell> month_data;
    callback month_clicked(int);

    border-radius: 2px;
    border-color: ghostwhite;

    // TODO add more cases for is_today & has_hover etc
    background: root.month_data.is_selected ? #4A90E2
              : root.month_data.is_current  ? #ddeeff
              : ta.has_hover                ? #f2f2f2
              : transparent;
    
    ta := TouchArea { clicked => { root.month_clicked(root.month_data.month-num); } }

    // TODO add more cases for is_today & has_hover etc
    VerticalLayout {
        alignment: space-evenly;

        Text {
            text: root.month_data.month_num;
            font-size: 13px;
            width: 100%;
            height: 15%;
            color: root.month_data.is_selected ? white
                : root.month_data.is_current  ? #2266cc
                : root.month_data.in_year     ? #a0a0a0
                : #bbbbbb;
            horizontal-alignment: center;
            vertical-alignment: top;
        }

        @children
    }
    
}


// Cells that will be present in the daily view, if an event is present
// Can span multiple hours
component EventCellButton inherits Rectangle {
    
}

// TODO change to ScrollView? prolly want custom scroll graphic
component DailyView inherits Rectangle {

    in property <length> hour_cell_width: 300px;
    in property <string> current_date: "Test Date";

    outer_hour := VerticalLayout {
        width: parent.width  - 20px;
        height: parent.height - 20px;
        min-width: date.min-width + hours_layout.min-width + 5px;
        min-height: date.min-height + hours_layout.min-height + 50px;

        date := Text {
            color: white;
            text: current_date;
            vertical-alignment: center;
            horizontal-alignment: left;
            height: 5%;
            width: 100%;
            min-width: hour_cell_width;
            min-height: parent.min-height * 5%;
        }

        hours_layout := VerticalLayout {
            height: 95%;
            width: 100%;

            min-width: hour_cell_width + 10px;
            min-height: parent.min-height * 78% + date.min-height + 10px;

            spacing: 2px;

            for h in 24 : HourCellButton {
                hour_data: {
                    hour_num: h+1, 
                    hour_type: HourStampType.Army,
                    time_signature: "test",
                    is_selected: false,
                    is_current: false,
                };
                //x: (root.width - self.width) / 2;
                min-width: hour_cell_width;
                min-height: 35px;
                height: 3%;
                drop-shadow-offset-y: 2px;
                drop-shadow-color: white;
            }

        }
    }
}

component MonthlyView inherits Rectangle {

    in property <length> day_cell_dims: 50px;
    in property <int> current_month: 1;
    in property <string> current_date_string;

    pure function get_monthly_day_count(month: int, leap_year: bool) -> int {
        return  month == 1  ? 31 
              : month == 3  ? 31
              : month == 4  ? 30
              : month == 5  ? 31
              : month == 6  ? 30
              : month == 7  ? 31
              : month == 8  ? 31
              : month == 9  ? 30
              : month == 10 ? 31
              : month == 11 ? 30
              : month == 12 ? 31
              : leap-year   ? 29 : 28;
    }

    outer_month := VerticalLayout {
        width: 100%;
        height: 95%;
        alignment: space-evenly;

        min-width: date.min-width + days_legend.min-width + days_grid.min-width + 5px;
        min-height: date.min-height + days_legend.min-height + days_grid.min-height + 5px;

        date := Text {
            font-weight: FontWeight.semi-bold;
            text: current_date_string;
            horizontal-alignment: center;
            vertical-alignment: center;
            color: #a4a4a4;
        }

        days_legend := HorizontalLayout {
            width: 100%;
            min-width: day_cell_dims * 7 + 5px;
            min-height: day_cell_dims + 5px;
            alignment: space-evenly;

            for days_list[d] in ["M", "T", "W", "T", "F", "S", "S"] : Text {

                font-weight: FontWeight.semi-bold;
                vertical-alignment: center;
                horizontal-alignment: center;
                min-width: day_cell_dims;
                min-height: day_cell_dims;
                text: days_list;
                color: #a4a4a4;
            }
        }

        days_grid := GridLayout {
            

            min-width: day_cell_dims * 7 + 5px;
            min-height: day_cell_dims * 6 + 5px;

            // TODO faulty, error prone, change it to per month day count
            for days[d] in get_monthly_day_count(current_month, false) : DayCellButton {
                col: Math.mod((d), 7);
                row: (d) / 7 ;

                min-width: day_cell_dims;
                min-height: day_cell_dims;

                day_data: {
                    day_num: (d+1),
                    in_month: true,
                    is_today: false,
                };
            }
        }

        
    }
}

component YearlyView inherits Rectangle {
    
    in property <int> current_year;
    in property <length> day_cell_dims: 25px;

    pure function get_monthly_day_count(month: int, leap_year: bool) -> int {
        return  month == 1  ? 31 
              : month == 3  ? 31
              : month == 4  ? 30
              : month == 5  ? 31
              : month == 6  ? 30
              : month == 7  ? 31
              : month == 8  ? 31
              : month == 9  ? 30
              : month == 10 ? 31
              : month == 11 ? 30
              : month == 12 ? 31
              : leap-year   ? 29 : 28;
    }

    outer_layout := VerticalLayout {

        min-width: year_text.min-width + months_grid.min-width;
        min-height: year_text.min-height + months_grid.min-height;

        alignment: space-evenly;

        year_text := Text {
            text: current_year;
            vertical-alignment: top;
            horizontal-alignment: center;
        }

        months_grid := GridLayout {
            
            spacing: 5px;
            padding-left: 5px;
            padding-right: 5px;
            padding-bottom: 10px;
            padding-top: 5px;
            

            for months[m] in ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] : MonthCellButton {
                
                col: Math.mod(m, 3);
                row: m / 3 ;

                width: 30%;
                
                
                //min-width: days_grid.min-width + 5px;
                //min-height: days_grid.min-height + day_cell_dims * 2;
                
                month_data: {
                    month_num: m,
                    in_year: true,
                    is_current: false,
                };

                days_grid := GridLayout {
                    //width: 90%;
                    //height: 85%;
                    //min-width: day_cell_dims * 7 + 5px;
                    //min-height: day_cell_dims * 6 + 5px;
                    for days[d] in get_monthly_day_count(m, false) : DayCellButton {
                        col: Math.mod((d), 7);
                        row: (d) / 7 ;

                        //min-width: day_cell_dims;
                        //min-height: day_cell_dims;

                        visible_days_num: true;

                        day_data: {
                            day_num: (d+1),
                            in_month: true,
                            is_today: false,
                        };
                    }
                }
            }
        }
    }
}

export component CalendarUI inherits PageComponent {
    title: @tr("Calendar Widget");
    description: @tr("A calendar widget with monthly, daily and yearly views.");
    show-enable-read-only: false;
    show-enable-page-widgets-switch: false;

    min-width: outer_layout.min-width;
    min-height: outer_layout.min-height;
    // preferred-width: 1000px;
    // preferred-height: 1200px;

    padding-left: 10px;
    padding-right: 10px;
    padding-bottom: 20px;
    padding-top: 10px;


    outer_layout := HorizontalLayout {

        min-width: month_year_layout.min-width + day_view.min-width + upcoming_notes_layout.min-width;
        min-height: month_year_layout.min-height + day_view.min-height + upcoming_notes_layout.min-height;
        height: 100%;
        width: 100%;
        spacing: 5px;

        month_year_layout := VerticalLayout {

            min-width: month_view.min-width + year_view.min-width;
            min-height: month_view.min-height + year_view.min-height;

            width: 30%;
            height: 90%;

            month_view := MonthlyView {
                width: 90%;
                height: 4%;
                current_date_string: "Test Date";
                day_cell_dims: 20px;
            }

            year_view := YearlyView {
                width: 90%;
                height: 60%;
                current_year: 2026;
                day_cell_dims: 23px;
            }
        }
        
        day_view := DailyView {

            current_date: "Test date";
            width: 40%;
            height: 90%;
            hour_cell_width: 50px;
        }

        upcoming_notes_layout := VerticalLayout {

            // upcoming view {}
            // day_num notes view {}

        }





    }

}
