
import { PageComponent } from "..\..\helpers\page_component.slint";
import { TextEdit, ScrollView } from "std-widgets.slint";
//import { GlobalConversionCallback } from "..\..\helpers\global_callbacks.slint";

//    Simple_AMPM, //  8:00 pm |  8:00 am
//    Full_AMPM,   // 08:00 pm | 08:00 am
//    Army_AMPM,   // 20:00 pm | 08:00 am
//    Simple,     // 20:00     |  8:00
//    Army,       // 20:00     | 08:00
enum HourStampType {
    Simple_AMPM,
    Full_AMPM,
    Army_AMPM,
    Simple,
    Army,
}

struct HourCell {
    hour_num: int, // 0 - 24
    hour_type: HourStampType,
    time_signature: string, // 8:00am / 20:00 / etc
    is_selected: bool,
    is_current: bool,
}

struct DayCell {
    day_num: int, // 1-31 unless its 30 day or february etc
    in_month: bool,
    is_today: bool,
    is_selected: bool,
}

struct MonthCell {
    month_num: int, // 1-12
    in_year: bool,
    is_current: bool,
    is_selected: bool,
}

struct EventCell {
    // idk what it should store yet, and if it needs to be on the slint side at all
}

// Cells that will be present in the daily view
component HourCellButton inherits Rectangle {
    in property <HourCell> hour_data;

    callback hour_clicked(int);

    pure function convert_time_to_signature(hour: int) -> string {
        return    root.hour_data.hour_type == HourStampType.Simple_AMPM ? hour < 12 ? 
                      hour + ":00 am" : hour + ":00 pm" 
                : root.hour_data.hour_type == HourStampType.Full_AMPM   ? hour < 10 ? 
                      "0" + hour + ":00 am" : hour < 12 ? hour + ":00 am" :
                      hour < 22 ? "0" + hour + ":00 pm" : hour + ":00 pm"
                : root.hour_data.hour_type == HourStampType.Army_AMPM   ? hour < 10 ?
                      "0" + hour + ":00 am" : hour < 12 ? hour + ":00 am" : hour + ":00 pm"  
                : root.hour_data.hour_type == HourStampType.Simple      ? hour < 12 ?
                      hour + ":00" : hour + ":00"  
                : root.hour_data.hour_type == HourStampType.Army        ? hour < 10 ? 
                      "0"+ hour + ":00" : hour + ":00"  
                : "UNDEFINED";
    }

    // TODO add more cases for is_today & has_hover etc
    // colors are for testing
    background: root.hour_data.is_selected                ? white
              : ta.has-hover                              ? #2266cc
              : Math.mod(root.hour_data.hour_num, 2) == 0 ? #2b2a2c 
              : #1f1f1f ; 

    ta := TouchArea { clicked => { root.hour_clicked(root.hour_data.hour_num); } }

    // TODO add more cases for is_today & has_hover etc
    Text {
        width: 100%;
        height: 100%;
        text: convert_time_to_signature(root.hour_data.hour-num);
        font-size: 13px;
        color: root.hour_data.is_selected ? white
             : root.hour_data.is_current  ? #2266cc
             : #bbbbbb;
        horizontal-alignment: left;
        vertical-alignment: top;
    }
}

// Cells that will be present in the Monthly and Yearly view
component DayCellButton inherits Rectangle {
    in property <DayCell> day_data;
    in property <bool> visible_days_num: true;

    callback day_clicked(int);

    border-radius: 12px;
    border-color: ghostwhite;
    border-width: 0px;

    // TODO add more cases for is_today & has_hover etc
    background: root.day_data.is_selected ? #4A90E2
              : root.day_data.is_today    ? #ddeeff
              : ta.has_hover              ? #1258a2
              : transparent;

    ta := TouchArea { clicked => { root.day_clicked(root.day_data.day_num); } }

    // TODO add more cases for is_today & has_hover etc
    Text {
        text: root.day_data.day_num;
        visible: visible_days_num;
        font-size: 14px;
        font-weight: FontWeight.semi-bold;
        color: root.day_data.is_selected ? white
             : root.day_data.is_today    ? #2266cc
             : root.day_data.in_month    ? #d6d6d6
             : #bbbbbb;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}

// Cells that will be present in the Yearly view
component MonthCellButton inherits Rectangle {

    in property <MonthCell> month_data;
    callback month_clicked(int);

    border-radius: 15px;
    border-color: Math.mod(root.month_data.month-num, 2) == 0 ? #272727 : #2d2d2d;
    border-width: 1px;

    // TODO add more cases for is_today & has_hover etc
    background: root.month_data.is_selected                 ? #4A90E2
              : root.month_data.is_current                  ? #ddeeff
              : ta.has_hover                                ? #1258a2
              : Math.mod(root.month_data.month-num, 2) == 0 ? #272727
              : transparent;
    
    ta := TouchArea { clicked => { root.month_clicked(root.month_data.month-num); } }

    // TODO add more cases for is_today & has_hover etc
    VerticalLayout {
        
        padding: 10px;

        Text {
            text: root.month_data.month_num;
            font-size: 13px;
            color: root.month_data.is_selected ? white
                : root.month_data.is_current  ? #2266cc
                : root.month_data.in_year     ? #a0a0a0
                : #bbbbbb;
            horizontal-alignment: center;
            vertical-alignment: top;

            
        }

        @children
    }
    
}


// Cells that will be present in the daily view, if an event is present
// Can span multiple hours
component EventCellButton inherits Rectangle {
    
}

// TODO change to ScrollView? prolly want custom scroll graphic
component DailyView inherits Rectangle {

    in property <length> hour_cell_width: 300px;
    in property <string> current_date: "Test Date";

    outer_hour := VerticalLayout {
        padding: 10px;
        padding-bottom: 20px;

        date := Text {
            color: white;
            text: current_date;
            vertical-alignment: center;
            horizontal-alignment: left;
            max-height: 50px;
        }

        hours_layout := VerticalLayout {

            spacing: 2px;

            for h in 24 : HourCellButton {
                hour_data: {
                    hour_num: h+1, 
                    hour_type: HourStampType.Army,
                    time_signature: "test",
                    is_selected: false,
                    is_current: false,
                };

                preferred-width: hour_cell_width;

                drop-shadow-offset-y: 2px;
                drop-shadow-color: #5e5e5f;
            }

        }
    }
}

component MonthlyView inherits Rectangle {

    in property <length> day_cell_dims: 50px;
    in property <int> current_month: 1;
    in property <string> current_date_string: "Test Date";

    pure function get_monthly_day_count(month: int, leap_year: bool) -> int {
        return  month == 1  ? 31 
              : month == 3  ? 31
              : month == 4  ? 30
              : month == 5  ? 31
              : month == 6  ? 30
              : month == 7  ? 31
              : month == 8  ? 31
              : month == 9  ? 30
              : month == 10 ? 31
              : month == 11 ? 30
              : month == 12 ? 31
              : leap-year   ? 29 : 28;
    }

    outer_month := VerticalLayout {
        padding: 5px;
        padding-bottom: 10px;

        days_grid := GridLayout {
            
            preferred-width: day_cell_dims * 7 + 5px;
            preferred-height: day_cell_dims * 6 + 5px;

            date := Text {
                
                col: 1;
                colspan: 4;
                row: 0;
                font-weight: FontWeight.semi-bold;
                font-size: 15px;
                letter-spacing: 1px;
                text: current_date_string;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: #a4a4a4;
                overflow: elide;
                wrap: no-wrap;
            }

            for days_list[d] in ["M", "T", "W", "T", "F", "S", "S"] : Text {
                col: d;
                row: 1;

                font-weight: FontWeight.semi-bold;
                font-size: 15px;
                vertical-alignment: center;
                horizontal-alignment: center;
                preferred-width: day_cell_dims;
                preferred-height: day_cell_dims;
                text: days_list;
                color: #a4a4a4;
            }

            // TODO faulty, error prone, change it to per month day count
            for days[d] in get_monthly_day_count(current_month, false) : DayCellButton {
                col: Math.mod((d), 7);
                row: ((d) / 7) + 2;

                preferred-width: day_cell_dims;
                preferred-height: day_cell_dims;

                day_data: {
                    day_num: (d+1),
                    in_month: true,
                    is_today: false,
                };
            }
        }

        
    }
}

component YearlyView inherits Rectangle {
    
    in property <int> current_year;
    in property <length> day_cell_dims: 25px;

    pure function get_monthly_day_count(month: int, leap_year: bool) -> int {
        return  month == 1  ? 31 
              : month == 3  ? 31
              : month == 4  ? 30
              : month == 5  ? 31
              : month == 6  ? 30
              : month == 7  ? 31
              : month == 8  ? 31
              : month == 9  ? 30
              : month == 10 ? 31
              : month == 11 ? 30
              : month == 12 ? 31
              : leap-year   ? 29 : 28;
    }

    outer_layout := VerticalLayout {

        min-width: year_text.min-width + months_grid.min-width;
        min-height: year_text.min-height + months_grid.min-height;

        alignment: start;

        year_text := Text {
            text: current_year;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        months_grid := GridLayout {
            
            spacing: 5px;
            padding: 10px;
            padding-bottom: 20px;
            height: 100%;

            for months[m] in ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] : MonthCellButton {
                
                col: Math.mod(m, 3);
                row: m / 3 ;
                
                min-height: day_cell_dims * 5;
                min-width: day_cell_dims * 6;

                month_data: {
                    month_num: m+1,
                    in_year: true,
                    is_current: false,
                };

                days_grid := GridLayout {

                    min-height: day_cell_dims * 4;
                    min-width: day_cell_dims * 5;

                    for days[d] in get_monthly_day_count(m+1, false) : DayCellButton {
                        col: Math.mod((d), 7);
                        row: (d) / 7 ;

                        visible_days_num: true;

                        // preferred-height: day_cell_dims;
                        // preferred-width: day_cell_dims;

                        day_data: {
                            day_num: (d+1),
                            in_month: true,
                            is_today: false,
                        };
                    }
                }
            }
        }
    }
}

struct UpcomingEventsCell {

    event_date: string,
    event_title: string,
    event_type: string, // TODO this will be changed to a user defined enum
    event_index: int,
    is_today: bool,
}

component UpcomingEventButton inherits Rectangle {

    in property <UpcomingEventsCell> event_data;

    callback upcoming_event_clicked(int);

    border-radius: 12px;
    border-color: ghostwhite;
    border-width: 0px;

    // TODO add more cases for is_today & has_hover etc
    background//: root.event_data.is_selected ? #4A90E2
              : root.event_data.is_today    ? #ddeeff
              : ta.has_hover              ? #1258a2
              : transparent;

    ta := TouchArea { clicked => { root.upcoming_event_clicked(root.event_data.event_index); } }

    // TODO add more cases for is_today & has_hover etc
    Text {
        text: root.event_data.event_title;
        font-size: 14px;
        font-weight: FontWeight.semi-bold;
        color//: root.event_data.is_selected ? white
             : root.event_data.is_today    ? #2266cc
             //: root.event_data.in_month    ? #d6d6d6
             : #bbbbbb;
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    
}

component UpcomingView inherits Rectangle {

    in property <[UpcomingEventsCell]> upcoming_events;
    
    outer_layout := VerticalLayout {
        padding: 5px;

        title_text := Text {
            text: "UPCOMING";
        }

        events_scroll_area := ScrollView {
            for event[e] in upcoming_events: UpcomingEventButton {
                
            }
        }
    }
}

component NotesView inherits Rectangle {
    
    // TODO add 'save' button

    in property <string> current_date: "Test Date";


    outer_layout := VerticalLayout {

        padding: 5px;
        spacing: 15px;


        date_text := Text {
            text: "Notes " + current_date;
        }

        notes_field := TextEdit {
            font-size: 12px;
        }
    }
}

export component CalendarUI inherits PageComponent {
    title: @tr("Calendar Widget");
    description: @tr("A calendar widget with monthly, daily and yearly views.");
    show-enable-read-only: false;
    show-enable-page-widgets-switch: false;

    // min-width: outer_layout.min-width;
    // min-height: outer_layout.min-height;
    // preferred-width: 1000px;
    // preferred-height: 1200px;

    padding-left: 10px;
    padding-right: 10px;
    padding-bottom: 20px;
    padding-top: 10px;


    outer_layout := HorizontalLayout {

        min-width: month_year_layout.min-width + day_view.min-width + upcoming_notes_layout.min-width;
        min-height: month_year_layout.min-height + day_view.min-height + upcoming_notes_layout.min-height;
        height: 100%;
        width: 100%;
        spacing: 5px;
        padding-bottom: 25px;

        month_year_layout := VerticalLayout {

            min-width: month_view.min-width + year_view.min-width;
            min-height: month_view.min-height + year_view.min-height;

            width: 30%;
            padding-bottom: 10px;
            

            month_view := MonthlyView {

                current_date_string: "Test Date";
                day_cell_dims: 20px;
            }

            year_view := YearlyView {

                current_year: 2026;
                day_cell_dims: 25px;
            }
        }
        
        day_view := DailyView {
            width: 45%;

            current_date: "Test date";

            hour_cell_width: 400px;
        }

        upcoming_notes_layout := VerticalLayout {
            padding-bottom: 14px;
            width: 25%;

            upcoming_view := UpcomingView {}
            notes_view := NotesView {}

        }





    }

}
