// Generated by luna_src/build.rs from the contents of tools/. Do not edit.
//
// Committed rather than gitignored so a fresh clone has working editor support
// before the first build. Adding or removing a tool folder rewrites this file,
// which is why adding a tool shows up in a diff.

#[path = "../../../tools/base_converter/mod.rs"]
pub(crate) mod base_converter;

#[path = "../../../tools/calendar/mod.rs"]
pub(crate) mod calendar;

use super::{ BoundTool, ToolView, ViewContext };

/// Every tool as the registry takes it: the manifest, and the background half
/// for a tool that declares one.
pub(crate) fn registrations()
-> Vec<(luna_core::ToolManifest, Option<luna_core::ServiceFactory>)> {
    return vec![
        (base_converter::Tool::manifest(), base_converter::Tool::service()),
        (calendar::Tool::manifest(), calendar::Tool::service()),
    ];
}

/// Binds every tool's callbacks and returns the bound views to be kept alive.
pub(crate) fn bind_all(
    ui: &slint::Weak<crate::LunaAppUi>,
    ctx: &ViewContext<'_>,
) -> Vec<Box<dyn BoundTool>> {
    return vec![
        Box::new(base_converter::Tool::bind(ui.clone(), ctx)),
        Box::new(calendar::Tool::bind(ui.clone(), ctx)),
    ];
}
