//! The tools compiled into this build.
//!
//! The module list, the manifest list and the binding list are all generated by
//! `build.rs` from whatever is in `tools/`. Adding a tool means dropping a folder in;
//! nothing in this file changes.
//!
//! A tool folder holds `manifest.toml`, a `mod.rs` defining `pub struct Tool`, and a
//! `ui.slint` exporting `component ToolPage`.

use luna_core::ToolManifest;
use slint::Weak;

use crate::LunaAppUi;

/// A tool view that has been bound to the window.
///
/// Object-safe, so bound views of different types can be held together and kept alive
/// for as long as the window is. Construction lives on [`ToolView`], which cannot be
/// object-safe because it builds `Self`.
pub(crate) trait BoundTool {
    /// The id of the tool this view belongs to.
    fn tool_id(&self) -> &'static str;
}

/// The UI half of a tool.
///
/// Implementors wire their Slint callbacks and hold whatever the page needs while it
/// is open. The background half is [`luna_core::ToolService`], which lives in the
/// registry and never touches Slint.
///
/// ## Lifecycle, and what it is not yet
///
/// The Slint page component is already created and destroyed on navigation, because
/// the generated page chain uses `if` and Slint instantiates conditionally. The Rust
/// binding is not: callbacks currently live on Slint globals, which exist for the life
/// of the window, so binding happens once at startup.
///
/// Moving bindings onto each page's own component instance, and with them true
/// per-open lifecycle, is what remains of the service/view split.
pub(crate) trait ToolView: BoundTool + Sized {
    /// The tool's manifest, parsed from the `manifest.toml` beside its source.
    ///
    /// Parsed rather than hand-built so the file stays the single source of truth. The
    /// build script parses the same file with the same type, so a manifest that builds
    /// is a manifest that loads.
    fn manifest() -> ToolManifest;

    /// Wires the tool's callbacks to the window.
    fn bind(ui: Weak<LunaAppUi>) -> Self;
}

// Written by build.rs from the contents of tools/. A plain module rather than an
// `include!` of OUT_DIR, so rust-analyzer resolves each tool's source and editing one
// gets completions and inline errors like any other file.
mod generated;

pub(crate) use generated::{ bind_all, manifests };
