import { Button, VerticalBox, LineEdit, GridBox } from "std-widgets.slint";

import { NumberConverter, ConversionCallback } from "pagesExport.slint";
import { SideBar } from "helpers/side-bar.slint";

export { ConversionCallback }


export component MyWindow inherits Window {
    preferred-height: 500px;
    preferred-width: 600px;
    title: "Tool Box";


    HorizontalLayout {
        sideBar := SideBar {
            title: "Tool Bar";
            model: ["Num Conv"];
        }

        if (sideBar.current-item == 0) : NumberConverter{}
    }
}
