import { Button, VerticalBox, LineEdit } from "std-widgets.slint";


export component MyWindow inherits Window {
    in-out property<int> number: 0;
    in-out property <string> converted: 0;
    callback request-convert-number(string);
    VerticalBox {
        LineEdit {
            input-type: decimal;
            text: "\{root.number}";
            placeholder-text: "Input a decimal number:";
            edited(number) => {
                root.request-convert-number(number);
            }
        }
        Text {
            text: root.converted;
        }
    }
}
